#
# Generates the contents of this repo's GitHub Pages page.
#
# For more details on workflows, see README.md.
#
name: Create Documentation on GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish to retype branch

    runs-on: ubuntu-latest

    steps:
      # See: https://github.com/actions/checkout
      - name: Clone Git repository
        uses: actions/checkout@v2
        with:
          lfs: true
          submodules: false # not needed

      - name: Build HTML files
        uses: retypeapp/action-build@v1

      - name: Publish HTML files to GitHub Pages
        uses: retypeapp/action-github-pages@v1
        with:
          update-branch: true
