#
# Generates the contents of this repo's GitHub Pages page.
#
# For more details on workflows, see README.md.
#
name: Create Documentation on GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

# Permissions for GITHUB_TOKEN for this workflow.
#   See: https://docs.github.com/en/actions/reference/authentication-in-a-workflow#permissions-for-the-github_token
permissions:
  contents: write

jobs:
  publish:
    name: Publish to retype branch

    runs-on: ubuntu-latest

    steps:
      # See: https://github.com/actions/checkout
      - name: Clone Git repository
        uses: actions/checkout@v3
        with:
          lfs: true
          submodules: false # not needed

      # Setting up .NET speeds up the build process (according to the documentation).
      # See: https://github.com/actions/setup-dotnet
      - name: Setup .NET build environment
        uses: actions/setup-dotnet@v2
        with:
          # NOTE: Apparently only the 3rd component can be "x"; i.e. "5.x" is not supported.
          dotnet-version: '6.0.x'

      # See: https://github.com/retypeapp/action-build
      - name: Build HTML files
        # For pinned versions, see: https://blog.gitguardian.com/github-actions-security-cheat-sheet/#use-specific-action-version-tags
        uses: retypeapp/action-build@21d0112281be2957ea1231796b5b50292cff5ebc # version 2.4.0

      # See: https://github.com/retypeapp/action-github-pages
      - name: Publish HTML files to GitHub Pages
        # For pinned versions, see: https://blog.gitguardian.com/github-actions-security-cheat-sheet/#use-specific-action-version-tags
        uses: retypeapp/action-github-pages@1207708b843b95c1a96b97a09fc4b2e747a1f0de # version 2.3.0
        with:
          # The branch where the results are stored
          branch: retype
          # Update the "retype" branch (instead of creating a new branch)
          update-branch: true
